title: Justice Sefas
email: jsefas@cs.ubc.ca
description: >- # this means to ignore newlines until "baseurl:"
   Research Homepage for Justice Sefas
baseurl: "/~jsefas" # the subpath to your homepage, typically /~username
url: "https://www.cs.ubc.ca" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jds8

nav:
 - name: Home
   link: "/"
 - name: Posts 
   link: "/posts/"
# - name: Code
#   link: "/code/"
# - name: People
#   link: "/people"
# - name: Teaching
#   link: "/teaching"
# - name: Talks
#   link: "/talks/"
# - name: Papers
#   link: "/papers"
# - name: "Bio"
#   link: "/bio"
# - name: "CV"
#   link: "/cv.pdf"
# - name: "Contact"
#   link: "/contact"


## don't edit below here unless you want to customize beyond
## changing the menus

markdown: kramdown

theme: jekyll-faculty-theme

kramdown:
  input: GFM
  default_lang: clojure
  syntax_highlighter: rouge

highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-scholar

scholar:
  style: apa
  repository: papers
  bibliography_template: bibliography
  bibliography_item_attributes:
    class: paper

# this is where you put your Google analytics tracking ID should you
# wish to use Google analytics (a good idea -- it's free)
tracking_id: #

sass:
  style: compressed
  sass_dir: _sass
